[package]
name = "bevyrpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy-yoleck = "0.14.1"
#bevy_mod_picking = "*"
#bevy_mod_ui_texture_atlas_image = "0.4.1"
anyhow = "1.0.86"
avian3d = "0.1.2"
#avian3d = { git = "https://github.com/Jondolf/avian" }
#avian_interpolation3d = { git = "https://github.com/janhohenheim/avian_interpolation" }
#avian_pickup = { git = "https://github.com/janhohenheim/avian_pickup" }
bevy = "0.14.0"
bevy-inspector-egui = "*"
bevy-scene-hook = "*"
bevy-tnua = "0.19.0"
bevy-tnua-avian3d = "0.1.1"
bevy-yoleck = "*"
bevy_asset_loader = {version = "0.21", features = ["2d"]}
bevy_egui = "*"
bevy_flycam = "*"
bevy_mod_static_inventory = "*"
bevy_registry_export = "*"
bevy_simple_text_input = "*"
bevy_sprite3d = "3.0"
bevy_yarnspinner = "*"
bevy_yarnspinner_example_dialogue_view = "*"
big-brain = "0.21.1"
blenvy = "0.1.0-alpha.1"
clap = { version = "*", features = ["derive"] }
lazy_static = "*"
leafwing-input-manager = "0.15.1"
oxidized_navigation = { git="https://github.com/TheGrimsey/oxidized_navigation.git", default-features = false, features = ["debug_draw", "avian"] }
rand = "*"
serde = "*"
sickle_ui = "0.2.1"
standard-dist = "*"

[profile.dev]
opt-level=3
