use avian_rerecast::AvianBackendPlugin;
use bevy::{input::common_conditions::input_just_pressed, prelude::*};
use bevy_landmass::{Agent, Agent3dBundle, AgentDesiredVelocity3d, AgentSettings, AgentTarget3d, Archipelago3d, ArchipelagoRef3d, Island, Landmass3dPlugin, Velocity3d, debug::{EnableLandmassDebug, Landmass3dDebugPlugin}};
use bevy_tnua::{builtins::{TnuaBuiltinWalkConfig, TnuaBuiltinWallSlideConfig}, control_helpers::TnuaSimpleAirActionsCounter, prelude::*};
use bevy_tnua::TnuaRigidBodyTracker;
use landmass::{ArchipelagoOptions, FromAgentRadius, PointSampleDistance3d};
use landmass_rerecast::{Island3dBundle, LandmassRerecastPlugin, NavMeshHandle3d};
use bevy_rerecast::prelude::*;

use crate::{GameState, Player, PlayerControlScheme, TnuaNpcController};

//#[derive(Resource)]
//struct NavMeshHandle(Handle<Navmesh>);

#[derive(Debug, Default, Component, Reflect)]
#[reflect(Component)]
pub struct DesiredPosition(pub Vec3);

#[derive(Debug, Clone, PartialEq, Component, Reflect)]
#[reflect(Component)]
pub struct Walk {
    /// Top speed on the ground
    pub speed: f32,
    /// Direction in which we want to walk and turn this tick.
    pub direction: Option<Dir3>,
}
impl Default for Walk {
    fn default() -> Self {
        Self {
            speed: 1.,
            direction: None,
        }
    }
}

#[derive(Debug, Component, Default)]
pub struct Obstacle;

#[derive(Debug, Default, Clone, PartialEq, Component, Reflect)]
#[reflect(Component)]
/// Must be larger than the height of the entity's center from the bottom of its
/// collider, or else the character will not float and Tnua will not work properly
pub struct FloatHeight(pub f32);

pub struct NavMeshPlugin;
impl Plugin for NavMeshPlugin {
    fn build(&self, app: &mut App) {
        app
            .add_plugins(Landmass3dPlugin::default())
            .add_plugins(Landmass3dDebugPlugin::default())
            .add_plugins(LandmassRerecastPlugin::default())
            .add_plugins(NavmeshPlugins::default())
            .add_plugins(AvianBackendPlugin::default())
            .register_type::<Walk>()
            .register_type::<FloatHeight>()
            .register_type::<DesiredPosition>()
            .add_systems(OnExit(GameState::Postload), landmass_rerecast_setup)
            .add_systems(Update, apply_walking)
            .add_systems(Update, toggle_landmass_debug.run_if(input_just_pressed(KeyCode::F12)));

    }
}

fn landmass_rerecast_setup(
    mut commands: Commands,
    mut generator: NavmeshGenerator,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    let archipelago = commands.spawn(
        Archipelago3d::new(ArchipelagoOptions {
            point_sample_distance: PointSampleDistance3d {
                distance_above: 0.5,
                distance_below: 2.5,
                ..PointSampleDistance3d::from_agent_radius(0.5)
            },
            ..ArchipelagoOptions::from_agent_radius(0.5)
        })
    ).id();

    // This island's nav mesh will be generated by `bevy_rerecast`!
    commands.spawn(Island3dBundle {
        island: Island,
        archipelago_ref: ArchipelagoRef3d::new(archipelago),
        nav_mesh: NavMeshHandle3d(
            generator.generate(NavmeshSettings { cell_size_fraction: 8., agent_radius: 0.5, ..Default::default() }),
        ),
    });
}

fn toggle_landmass_debug(mut debug: ResMut<EnableLandmassDebug>) {
    **debug = !**debug;
}

fn apply_walking(
    mut character_query: Query<(&mut TnuaController<PlayerControlScheme>, &AgentDesiredVelocity3d, &mut Velocity3d, &TnuaRigidBodyTracker), Without<Player>>,
) {
    trace!("SYSTEM: apply_walking");

    for (mut controller, desired_velocity, mut agent_velocity, tracker) in &mut character_query {
        controller.initiate_action_feeding();
        let Ok(direction) = Dir3::new(desired_velocity.velocity()) else { 
            controller.basis = TnuaBuiltinWalk { desired_motion: desired_velocity.velocity().normalize_or_zero(), desired_forward: None };
            agent_velocity.velocity = tracker.velocity;
            return;
        };
        controller.basis = TnuaBuiltinWalk { desired_motion: desired_velocity.velocity().normalize_or_zero(), desired_forward: Some(direction) };
        agent_velocity.velocity = tracker.velocity;
    }
}
