use avian3d::{prelude::{Collider, RigidBody}};
use avian_rerecast::AvianBackendPlugin;
use bevy::{input::common_conditions::input_just_pressed, prelude::*};
use bevy_landmass::{Agent, Agent3dBundle, AgentDesiredVelocity3d, AgentSettings, AgentTarget3d, Archipelago3d, ArchipelagoRef3d, Island, Landmass3dPlugin, debug::{EnableLandmassDebug, Landmass3dDebugPlugin}};
use bevy_tnua::prelude::*;
use bevy_tnua_avian3d::{TnuaAvian3dPlugin, TnuaAvian3dSensorShape};
use landmass::{ArchipelagoOptions, FromAgentRadius, PointSampleDistance3d};
use landmass_rerecast::{Island3dBundle, LandmassRerecastPlugin, NavMeshHandle3d};
use bevy_rerecast::prelude::*;

use crate::{GameState, Player};

//#[derive(Resource)]
//struct NavMeshHandle(Handle<Navmesh>);

#[derive(Debug, Default, Component, Reflect)]
#[reflect(Component)]
pub struct DesiredPosition(pub Vec3);

#[derive(Debug, Clone, PartialEq, Component, Reflect)]
#[reflect(Component)]
pub struct Walk {
    /// Top speed on the ground
    pub speed: f32,
    /// Direction in which we want to walk and turn this tick.
    pub direction: Option<Dir3>,
}
impl Default for Walk {
    fn default() -> Self {
        Self {
            speed: 1.,
            direction: None,
        }
    }
}

#[derive(Debug, Component)]
pub struct Obstacle;

#[derive(Debug, Default, Clone, PartialEq, Component, Reflect)]
#[reflect(Component)]
/// Must be larger than the height of the entity's center from the bottom of its
/// collider, or else the character will not float and Tnua will not work properly
pub struct FloatHeight(pub f32);

pub struct NavMeshPlugin;
impl Plugin for NavMeshPlugin {
    fn build(&self, app: &mut App) {
        app
            .add_plugins(Landmass3dPlugin::default())
            .add_plugins(Landmass3dDebugPlugin::default())
            .add_plugins(LandmassRerecastPlugin::default())
            .add_plugins(NavmeshPlugins::default())
            .add_plugins(AvianBackendPlugin::default())
            .register_type::<Walk>()
            .register_type::<FloatHeight>()
            .register_type::<DesiredPosition>()
            .add_plugins(TnuaAvian3dPlugin::new(FixedUpdate))
            .add_plugins(TnuaControllerPlugin::new(FixedUpdate))
            .add_systems(OnEnter(GameState::Gameplay), landmass_rerecast_setup)
            .add_systems(Update, apply_walking)
            .add_systems(Update, toggle_landmass_debug.run_if(input_just_pressed(KeyCode::F12)));

    }
}

fn landmass_rerecast_setup(
    mut commands: Commands,
    mut generator: NavmeshGenerator,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    let archipelago = commands.spawn(
        Archipelago3d::new(ArchipelagoOptions {
            point_sample_distance: PointSampleDistance3d {
                distance_above: 0.5,
                distance_below: 0.5,
                ..PointSampleDistance3d::from_agent_radius(0.5)
            },
            ..ArchipelagoOptions::from_agent_radius(0.5)
        })
    ).id();

    // This island's nav mesh will be generated by `bevy_rerecast`!
    commands.spawn(Island3dBundle {
        island: Island,
        archipelago_ref: ArchipelagoRef3d::new(archipelago),
        nav_mesh: NavMeshHandle3d(
            generator.generate(NavmeshSettings { agent_radius: 0.5, ..Default::default() }),
        ),
    });

    // Create an agent that will find a path as soon as the nav mesh is generated.
    commands.spawn((
            Agent3dBundle {
                agent: Agent::default(),
                archipelago_ref: ArchipelagoRef3d::new(archipelago),
                settings: AgentSettings {
                    desired_speed: 5.0,
                    max_speed: 10.0,
                    radius: 0.5
                },
            },
            Transform::from_xyz(-5.0, 0.5, -15.0),
            AgentTarget3d::Point(Vec3::new(15.0, 0.5, 15.0)),
            Mesh3d(meshes.add(Cuboid::new(1.0, 1.0, 1.0))),
            MeshMaterial3d(materials.add(Color::WHITE)),
            RigidBody::Dynamic,
            Collider::cuboid(1.0, 1.0, 1.0),
    ))
    .insert(TnuaController::default())
    .insert(TnuaAvian3dSensorShape(Collider::cuboid(0.5, 0.5, 0.5)))
    .insert(FloatHeight(0.5))
    .insert(Walk::default())
    .insert(Name::new("Walking Cube"));
}

fn toggle_landmass_debug(mut debug: ResMut<EnableLandmassDebug>) {
    **debug = !**debug;
}

fn apply_walking(
    mut character_query: Query<(&mut TnuaController, &mut Walk, &FloatHeight, &AgentDesiredVelocity3d), Without<Player>>,
) {
    trace!("SYSTEM: apply_walking");

    for (mut controller, mut walking, float_height, desired_velocity) in &mut character_query {
        let Ok(direction) = Dir3::new(desired_velocity.velocity()) else { return };
        let speed = walking.speed;
        controller.basis(TnuaBuiltinWalk {
            desired_velocity: direction * speed,
            desired_forward: Some(direction),
            float_height: float_height.0,
            cling_distance: 1.0,
            ..Default::default()
        });
        walking.direction = None;
    }
}
